In [3]:
import numpy as np
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a ** 2)


print(a > b)
print(a==b)
print(a <= b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[ 100  400  900 1600]
[ True  True  True  True]
[False False False False]
[False False False False]


In [4]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))
print(np.abs(np.array([-1,-2,3])))


[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[     10     400   27000 2560000]
[0 0 0 0]
[1 2 3]


In [6]:
a=np.array([10,20,30,40,50])
print(a[0])
print(a[3])


b=np.array([[1,2,3],[4,5,6]])
print(b[1,2])

10
40
6


In [7]:
a=np.array([10,20,30,40,50])
print(a[1:4])
print(a[:3])
print(a[2:])

[20 30 40]
[10 20 30]
[30 40 50]


In [8]:
a=np.array([10,20,30,40,50])
idx=[0,2,4]
print(a[idx])

[10 30 50]


In [11]:
a=np.array([10,15,20,25,30])
print(a)
mask = a >18 
print(mask)
print(a[mask])
print(a[a%10==0])

[10 15 20 25 30]
[False False  True  True  True]
[20 25 30]
[10 20 30]


In [12]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [16]:
a=np.array([10,15,20,25,30,35,40,45])
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.percentile(a,75))
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))

220
27.5
27.5
11.4564392373896
131.25
10
45
36.25
[3.16227766 3.87298335 4.47213595 5.         5.47722558 5.91607978
 6.32455532 6.70820393]
[2.30258509 2.7080502  2.99573227 3.21887582 3.40119738 3.55534806
 3.68887945 3.80666249]
[2.20264658e+04 3.26901737e+06 4.85165195e+08 7.20048993e+10
 1.06864746e+13 1.58601345e+15 2.35385267e+17 3.49342711e+19]
[-0.54402111  0.65028784  0.91294525 -0.13235175 -0.98803162 -0.42818267
  0.74511316  0.85090352]


In [21]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate([a,b]))
print(np.vstack([a,b]))
print(np.hstack([a,b]))
print(np.stack([a,b], axis=0))



[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [27]:
a=np.array([1,2,3])
print(np.append(a,[4,5]))
print(np.insert(a,1,99))
print(np.delete(a,0))
print(a)

[1 2 3 4 5]
[ 1 99  2  3]
[2 3]
[1 2 3]


In [23]:
a=np.arange(9)
print(a)
np.split(a, 3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [30]:
a=np.array([3,1,4,1,5,9,2])
print(a)
b=np.sort(a)
print(a)
print(b)
print(np.unique(a))
print(a[::-1])


[3 1 4 1 5 9 2]
[3 1 4 1 5 9 2]
[1 1 2 3 4 5 9]
[1 2 3 4 5 9]
[2 9 5 1 4 1 3]


In [ ]:
matrix=np.array([])