In [16]:
# Project:Student Marks Analysis System
# This walkthrough build a small realistic pipeline using only NUMPY
# Have a [articipants type each step along with you pause after each block to check output
# Step 1- Dataset Creation
# Steo 2- Average marks per student
# Step 3- Highest and Lowest marks
# Step 4- Standard deviation per Student
# Step 5- Ranking Students
# Step 6- Top Students(Above class average)
# Step 7-Subject wise analysis
# Step 8- percentage calculation
# Step 9- Visualization Ready data









import numpy as np
students = np.array(["Shivam","Riya","Priya","Utkarsh","Aditi"])
subjects = np.array(["Python","C","C++","Java","Java Script"])
marks = np.array([
    [85, 90, 78, 92, 88],
    [76, 81, 85, 79, 80],
    [90, 88, 92, 95, 91],
    [65, 70, 72, 68, 74],
    [88, 84, 80, 86, 90]
])
print("Students: ",students)
print("Subjects: ",subjects)
print("Marks: ",marks)
print(marks.shape)
print(marks.dtype)
print(marks.size)
print(marks.ndim)
average_marks=np.mean(marks,axis=0)
print("Average Marks:",average_marks)


for i in range(len(students)):
    print(students[i],":",average_marks[i],2)


highest_marks = np.max(marks, axis=1)
print(highest_marks)

lowest_marks = np.min(marks, axis=1)
print(lowest_marks)


for i in range(len(students)):
    print(students[i])
    print("Highest:", highest_marks[i])
    print("Lowest :", lowest_marks[i])


std_deviation = np.std(marks, axis=1)
print(std_deviation)



rank = np.argsort(average_marks)[::-1]

print("STUDENT LEADERBOARD\n")

for i in range(len(rank)):
    print("Rank", i + 1)
    print("Student :", students[rank[i]])
    print("Average :", round(average_marks[rank[i]], 2))
    print("-" * 35)
topper = rank[0]
print("\nTopper :", students[topper])
print("Average :", round(average_marks[topper], 2))

last = rank[-1]
print("\nLast Rank :", students[last])
print("Average :", round(average_marks[last], 2))


    

Students:  ['Shivam' 'Riya' 'Priya' 'Utkarsh' 'Aditi']
Subjects:  ['Python' 'C' 'C++' 'Java' 'Java Script']
Marks:  [[85 90 78 92 88]
 [76 81 85 79 80]
 [90 88 92 95 91]
 [65 70 72 68 74]
 [88 84 80 86 90]]
(5, 5)
int64
25
2
Average Marks: [80.8 82.6 81.4 84.  84.6]
Shivam : 80.8 2
Riya : 82.6 2
Priya : 81.4 2
Utkarsh : 84.0 2
Aditi : 84.6 2
[92 85 95 74 90]
[78 76 88 65 80]
Shivam
Highest: 92
Lowest : 78
Riya
Highest: 85
Lowest : 76
Priya
Highest: 95
Lowest : 88
Utkarsh
Highest: 74
Lowest : 65
Aditi
Highest: 90
Lowest : 80
[4.88262225 2.92574777 2.31516738 3.12409987 3.44093011]
STUDENT LEADERBOARD

Rank 1
Student : Aditi
Average : 84.6
-----------------------------------
Rank 2
Student : Utkarsh
Average : 84.0
-----------------------------------
Rank 3
Student : Riya
Average : 82.6
-----------------------------------
Rank 4
Student : Priya
Average : 81.4
-----------------------------------
Rank 5
Student : Shivam
Average : 80.8
-----------------------------------

Topper : Aditi
Aver